### ISSUE TITLE
Deprecation warnings with latest astropy version

### ISSUE THREAD

**Issue by rmjarvis** [timj/starlink-pyast#2]
After upgrading to the latest astropy version (0.4.2), I started getting DeprecationWarnings from my code that uses starlink.Ast.  

In particular, the line `fc = starlink.Ast.FitsChan( starlink.Atl.PyFITSAdapter(hdu) )`.  (The `hdu` is an astropy.io.fits hdu.)

The code still works correctly, but it emits:
```
WARNING: AstropyDeprecationWarning: The ascard function is deprecated and may be removed in a future version.
        Use the `.cards` attribute instead. [astropy.utils.misc]
WARNING: AstropyDeprecationWarning: The CardList class has been deprecated; all its former functionality has been subsumed by the Header class, so CardList objects should not be directly created.  See the PyFITS 3.1.0 CHANGELOG for more details. [astropy.io.fits.card]
WARNING: AstropyDeprecationWarning: The ascard function is deprecated and may be removed in a future version.
        Use the `.cards` attribute instead. [astropy.utils.misc]
WARNING: AstropyDeprecationWarning: The ascardimage function is deprecated and may be removed in a future version.
        Use the `.image` attribute instead. [astropy.utils.misc]
```
In GalSim, we similarly try to support both pyfits and astropy.io.fits as our fits front end, so the changes in syntax over the various versions have been a bit of a pain.  We guard most of our "pyfits" usage with if statements that check which version we are using.  I think it shouldn't be too hard to do a similar thing here to avoid these warnings and use the more recent recommended syntax when "pyfits" is really astropy.io.fits.

Thanks.

**Comment by timj** [comment]
I think #5 fixes this.
